
<jsp:useBean id="erapidBean" class="com.csgroup.general.ErapidBean" scope="application"/>
<jsp:useBean id="convertor" class="com.csgroup.general.Convertor" scope="application"/>
<jsp:useBean id="userSession" class="com.csgroup.general.UserSession" scope="session"/>
<%
if(erapidBean.getServerName()==null||erapidBean.getServerName().equals("null")||erapidBean.getServerName().trim().length()==0){
        erapidBean.setServerName("server1");
}
try{
%>
<META http-equiv=Content-Type content="text/html; charset=utf-8">


<%@ page language="java" contentType="text/html; charset=UTF-8" import="java.util.*" import="java.sql.*" import="java.net.*" import="java.io.*" import="javax.mail.*" import="java.util.*" import="java.math.*" import="java.sql.*" import="javax.mail.internet.*" import="javax.activation.*" import="java.net.*" import="java.text.*" errorPage="error.jsp" %>


<%@ include file="../../db_con.jsp"%>
<%@ include file="../../db_con_psa.jsp"%>
<%
out.println(userSession.getEmail()+":: user id");
out.println("<font size='2' color='red'>Please do not close this window.  It will close itself when it is finished.</font><BR>");
String order_no=request.getParameter("order_no");
String creator_id="";
String email="";
String message=order_no+":: Quote Number \n ";
String message_footer="";
String host ="LEBHQ-SMTP01.c-sgroup.com";

String from="ADSNEWTRANSFERS@c-sgroup.com";
String QuoteID="";
String AcctID="";
String projectType="";
String assignedRepNo="";
String baseQuoteNo="";
ResultSet rs2=stmt.executeQuery("select product_id,creator_id, project_NAME,project_type_id,cust_name,project_type,assigned_rep_no,base_quote_no from cs_project where order_no='"+order_no.trim()+"'");
if(rs2 != null){
	while(rs2.next()){
		creator_id=rs2.getString(2);
		message=message+rs2.getString(3)+" \n ";
		QuoteID=rs2.getString(4);
		AcctID=rs2.getString(5);
		projectType=rs2.getString("project_type");
		assignedRepNo=rs2.getString("assigned_rep_no");
		baseQuoteNo=rs2.getString("base_quote_no");
	}
}
rs2.close();
int counter=0;
if(assignedRepNo==null || assignedRepNo.trim().length()==0){
	while((assignedRepNo==null||assignedRepNo.trim().length()==0)&&(baseQuoteNo != null && baseQuoteNo.trim().length()>0&&baseQuoteNo.substring(0,6).equals(order_no.substring(0,6)))){
		if(counter>20){
			assignedRepNo="0";
		}
		ResultSet rs2x=stmt.executeQuery("select product_id,creator_id, project_NAME,project_type_id,cust_name,project_type,assigned_rep_no,base_quote_no from cs_project where order_no='"+baseQuoteNo.trim()+"'");
		if(rs2x != null){
			while(rs2x.next()){
				assignedRepNo=rs2x.getString("assigned_rep_no");
				baseQuoteNo=rs2x.getString("base_quote_no");
			}
		}
		rs2x.close();
	}
}
if(AcctID==null){
	AcctID="";
}
out.println(AcctID+"::acctid<BR>");
out.println(QuoteID+"::quoteid<BR><BR><BR>");
if(projectType !=null && projectType.equals("SFDC")){
	if(assignedRepNo != null && assignedRepNo.trim().length()>0){
		creator_id=assignedRepNo;
	}
}
else{
	ResultSet rstest=stmt_psa.executeQuery("SELECT * FROM dba.quotes_issued where quote_id='"+QuoteID+"'");
	if(rstest != null){
		while(rstest.next()){
			creator_id=rstest.getString(4);
		}
	}
	rstest.close();
		ResultSet rs_psa_contact = stmt_psa.executeQuery("SELECT * FROM dba.contact where cont_id like '"+creator_id+"'");
			if (rs_psa_contact !=null) {
		while (rs_psa_contact.next()) {
					AcctID=rs_psa_contact.getString(2);
		}
		}
		rs_psa_contact.close();
	if(AcctID.trim().length()>0){
		ResultSet rs_psa_account = stmt_psa.executeQuery("SELECT alias FROM dba.account where acct_id like '"+AcctID+"'");
			if (rs_psa_account !=null) {
			while (rs_psa_account.next()) {
				if(rs_psa_account.getString(1)!= null && !rs_psa_account.getString(1).trim().equals("null")){
						creator_id=rs_psa_account.getString(1);
				}
				}
			}
			rs_psa_account.close();
	}
}
String tempcontactname="";
ResultSet rs3=stmt.executeQuery("select contact_name, contact_email,rep_no from cs_sbu_contacts where rep_no in ('"+creator_id+"','0') and product_id='ads' order by rep_no");
if(rs3 != null){
	while(rs3.next()){
		tempcontactname=rs3.getString(1);
		//message=message+rs3.getString(1)+" \n ";
		email=rs3.getString(2);
		out.println(tempcontactname+"::"+email+"::"+rs3.getString(3)+"::<BR>");
	}
}
rs3.close();
message=message+"Final Pricing required by \n "+tempcontactname+" \n ";

out.println(creator_id+"::"+email+"::"+from);

try{

	message_footer=message_footer+"\n\n\n[THIS MESSAGE WAS AUTOGENERATED BY CONSTRUCTION SPECIALTIES QUOTE SYSTEM]";
	message_footer=message_footer+"\n====================";
	message_footer=message_footer+"\nThis email message and any files transmitted with it is for the sole ";
	message_footer=message_footer+"\nuse of the intended recipient(s) and may contain confidential and privileged ";
	message_footer=message_footer+"\ninformation. Any unauthorized review, use, disclosure or distribution of this";
	message_footer=message_footer+"\nemail content is prohibited. If you are not the intended recipient, please";
	message_footer=message_footer+"\ndestroy all paper and electronic copies of the original message.";
	message_footer=message_footer+"\n====================";
	Properties prop =System.getProperties();
	prop.put("mail.smtp.host",host);
	Session ses1  = Session.getDefaultInstance(prop,null);
	MimeMessage msg = new MimeMessage(ses1);
	msg.addFrom(new InternetAddress().parse(email));
	msg.setReplyTo(new InternetAddress().parse(email));
//email="gsuisham@c-sgroup.com";
	msg.addRecipients(Message.RecipientType.TO,new InternetAddress().parse(email));
	msg.addRecipients(Message.RecipientType.CC,new InternetAddress().parse("mmiller@c-sgroup.com"));
	msg.addRecipients(Message.RecipientType.CC,new InternetAddress().parse(userSession.getEmail()));
	msg.setSubject(order_no+"  Final Pricing Required ");
	BodyPart messageBodyPart = new MimeBodyPart();
	messageBodyPart.setText(message);
	Multipart multipart = new MimeMultipart();
	multipart.addBodyPart(messageBodyPart);
	msg.setContent(multipart);
	messageBodyPart = new MimeBodyPart();
	messageBodyPart.setText(message_footer);
	multipart.addBodyPart(messageBodyPart);
	Transport.send(msg);
	out.println(" An Email has been successfully delivered<br> to following recipients:<br> "+email+"<br>");
}
catch(javax.mail.internet.AddressException ae){
	ae.printStackTrace();
	out.println(ae);
}
catch(javax.mail.MessagingException me){
	me.printStackTrace();
	out.println(me);
}
catch(Exception e){
	e.printStackTrace();
	out.println(e);
}


stmt.close();
myConn.close();
stmt_psa.close();
myConn_psa.close();
}
catch(Exception e){
out.println(e);
}
%>

<body onload='javascript:window.close();'>-->
</body>