
<%

try{

%>
<html>
	<head>
		<title>Order Write-up sheet Mailing</title>
		<link rel='stylesheet' href='../../../style1.css' type='text/css'/>
	</head>

	<h1>EMail Notification::</h1>
	<%@ page language="java" import="javax.mail.*" import="java.util.*" import="java.math.*" import="java.sql.*" import="javax.mail.internet.*" import="javax.activation.*" import="java.net.*" import="java.text.*" errorPage="error.jsp" %>

	<%
	
	
	
	//String name= userId;
	//String product_id="";
	String quote_originMail="";
	//String order_no = request.getParameter("order_no");
	String project_name = "";
	String sections = request.getParameter("sections");
	//String rep_no = thisRep;
	String from = "Erapid_Order_"+order_no+"_confirmation@c-sgroup.com" ;
	if(!from.trim().endsWith("@c-sgroup.com")){
		from="no_reply_ows@c-sgroup.com";
	}
	//String to = request.getParameter("to");
	String cc = "";
	//String environment = request.getParameter("environment");
	String rep_message = messageForMail;
	String rep_info="";
	
	
	
	//HttpSession UserSession1 = request.getSession();
	//String name=UserSession1.getAttribute("username").toString();
	/*String name= request.getParameter("name");
	String product_id="";
	String quote_originMail="";
	String order_no = request.getParameter("order_no");
	String project_name = "";
	String sections = request.getParameter("sections");
	String rep_no = request.getParameter("rep_no");
	String from = request.getParameter("from") ;
	if(!from.trim().endsWith("@c-sgroup.com")){
		from="no_reply_ows@c-sgroup.com";
	}
	String to = request.getParameter("to");
	String cc = request.getParameter("cc");
	String environment = request.getParameter("environment");
	String rep_message = request.getParameter("message");
	String rep_info="";*/
	
	

	try{
		//out.println("1");
		ResultSet rsmail=stmt.executeQuery("select * from cs_reps where rep_no='"+rep_no+"'");
		if(rsmail != null){
			while(rsmail.next()){
				rep_info=rsmail.getString("rep_account")+"\r\n\n ";
				rep_info=rep_info+rsmail.getString("telephone")+"\r\n\n ";
				rep_info=rep_info+rsmail.getString("email");

			}
		}
		rsmail.close();
		ResultSet rs_projectmail = stmt.executeQuery("SELECT project_name,product_id,quote_origin FROM cs_project where Order_no like '"+order_no+"' ");
		if (rs_projectmail !=null) {
			while (rs_projectmail.next()) {
				product_id= rs_projectmail.getString("product_id");
				project_name = rs_projectmail.getString("project_name");
			}
		}
		rs_projectmail.close();
		//String host ="lebhq-notes.c-sgroup.com";
		String host ="LEBHQ-SMTP01.c-sgroup.com";
		String subject = "Construction Specialties Order Sheet "+order_no+" for \'"+project_name+"\' Project";
		String messagemail = "";
		messagemail = messagemail+"Attached Below is the Construction Specialties Order Write-up sheet for Erapid order::"+order_no+".";
		//message = message+"\r\nProject:: \'"+order_no+"\' ";
		//			message=message+"\r\n\n Contact Info: "+rep_info ;
		messagemail=messagemail+" \r\n\n "+rep_message+" \r\n\n";
		String localfile = "d:\\custom\\quotes\\images\\cs_logo.jpg";
		String attachName = "Order sheet -"+order_no+".html";
		String urlmail="";
		String message_footer="\r\n";
		message_footer=message_footer+"\n\n\n[THIS MESSAGE WAS AUTOGENERATED BY CONSTRUCTION SPECIALTIES QUOTE SYSTEM]";
		message_footer=message_footer+"\n====================";
		message_footer=message_footer+"\nThis email message and any files transmitted with it is for the sole ";
		message_footer=message_footer+"\nuse of the intended recipient(s) and may contain confidential and privileged ";
		message_footer=message_footer+"\ninformation. Any unauthorized review, use, disclosure or distribution of this";
		message_footer=message_footer+"\nemail content is prohibited. If you are not the intended recipient, please";
		message_footer=message_footer+"\ndestroy all paper and electronic copies of the original message.";
		message_footer=message_footer+"\n====================";
		//url= ""+application.getInitParameter("HOST")+"/erapid/us/orders/ows/order_sheet.jsp?sections="+sections+"&rep_no="+rep_no.trim()+"&orderNo="+order_no;
		urlmail= "https://sfxt.c-sgroup.com:8443/ows_webapp/OWS/JSP/order_sheet.jsp?sections="+sections+"&rep_no="+rep_no.trim()+"&userId="+userId+"&orderNo="+order_no;
		//out.println(urlmail);
		Properties prop =System.getProperties();
		prop.put("mail.smtp.host",host);
		Session ses1  = Session.getDefaultInstance(prop,null);
		MimeMessage msg = new MimeMessage(ses1);
		msg.addFrom(new InternetAddress().parse(from));
		//to="praveensannadi@gmail.com";
		//cc="gregsuisham@gmail.com";
		//out.println(from+" EMAILS ARE REDIRECTED TO JIM AND GREG FOR TESTING "+to);
		msg.addRecipients(Message.RecipientType.TO,new InternetAddress().parse(to.trim()));
		msg.addRecipients(Message.RecipientType.CC,new InternetAddress().parse(cc));
		msg.setSubject(subject);
		// Create the message part  
		BodyPart messageBodyPart = new MimeBodyPart();
		// Fill the message
		messageBodyPart.setText(messagemail);
		Multipart multipart = new MimeMultipart();
		multipart.addBodyPart(messageBodyPart);
		// Part two is attachment
		messageBodyPart = new MimeBodyPart();
		DataSource sourceMail = new URLDataSource(new URL(urlmail));
		messageBodyPart.setDataHandler(new DataHandler(sourceMail));
		messageBodyPart.setFileName(attachName);
		multipart.addBodyPart(messageBodyPart);
		msg.setContent(multipart);
		//adding the footer
		messageBodyPart = new MimeBodyPart();
		messageBodyPart.setText(message_footer);
		multipart.addBodyPart(messageBodyPart);
		if(quote_originMail==null){
			quote_originMail="";
		}
		//out.println("testingEmail");
		if(to.toUpperCase().indexOf("C-SGROUP")<0){
			//out.println("HERE"+environment);
			Transport.send(msg);
			out.println(" An Email has been successfully delivered<br> to following recipients:<br> "+to+"<br>"+cc);
			if(environment.indexOf("dev")>=0 || environment.indexOf("sit")>=0){
				if(!(product_id.equals("ADS")&&(quote_originMail.equals("As Build")||quote_originMail.equals("change")||quote_originMail.equals("release")||quote_originMail.equals("revision")||quote_originMail.equals("submittal")))){
					Transport.send(msg);
					out.println(" An Email has been successfully delivered<br> to following recipients:<br> "+to+"<br>"+cc);


					String insert ="INSERT INTO cs_ows_transfer_email_log([order_no],[time_sent],[rep_no],[product_id],[from_email],[to_email],[user_id])VALUES(?,?,?,?,?,?,?) ";
					PreparedStatement update_mat_shop_orders = myConn.prepareStatement(insert);
					update_mat_shop_orders.setString(1,order_no);
					update_mat_shop_orders.setTimestamp(2,new java.sql.Timestamp(Calendar.getInstance().getTime().getTime()));
					update_mat_shop_orders.setString(3,rep_no);
					update_mat_shop_orders.setString(4,product_id);
					update_mat_shop_orders.setString(5,from);
					update_mat_shop_orders.setString(6,to);
					update_mat_shop_orders.setString(7,userId);
					int rocount = update_mat_shop_orders.executeUpdate();
					update_mat_shop_orders.close();
				}
				else{
					out.println("ads release");
				}
				//out.println("HERE");
			}
		}

	}
	catch(javax.mail.internet.AddressException ae){
		ae.printStackTrace();
		out.println(ae+"::1<BR>");
		String insert ="INSERT INTO cs_ows_transfer_email_log([order_no],[time_sent],[rep_no],[product_id],[from_email],[to_email],[user_id])VALUES(?,?,?,?,?,?,?) ";

		PreparedStatement update_mat_shop_orders = myConn.prepareStatement(insert);
		update_mat_shop_orders.setString(1,order_no);
		update_mat_shop_orders.setTimestamp(2,new java.sql.Timestamp(Calendar.getInstance().getTime().getTime()));
		update_mat_shop_orders.setString(3,rep_no);
		update_mat_shop_orders.setString(4,"ERROR1");
		update_mat_shop_orders.setString(5,from);
		update_mat_shop_orders.setString(6,to);
		update_mat_shop_orders.setString(7,userId);
		int rocount = update_mat_shop_orders.executeUpdate();
		update_mat_shop_orders.close();
	}
	catch(javax.mail.MessagingException me){
		me.printStackTrace();
		out.println(me+"::2<BR>");
		String insert ="INSERT INTO cs_ows_transfer_email_log([order_no],[time_sent],[rep_no],[product_id],[from_email],[to_email],[user_id])VALUES(?,?,?,?,?,?,?) ";

		PreparedStatement update_mat_shop_orders = myConn.prepareStatement(insert);
		update_mat_shop_orders.setString(1,order_no);
		update_mat_shop_orders.setTimestamp(2,new java.sql.Timestamp(Calendar.getInstance().getTime().getTime()));
		update_mat_shop_orders.setString(3,rep_no);
		update_mat_shop_orders.setString(4,"ERROR2");
		update_mat_shop_orders.setString(5,from);
		update_mat_shop_orders.setString(6,to);
		update_mat_shop_orders.setString(7,userId);
		int rocount = update_mat_shop_orders.executeUpdate();
		update_mat_shop_orders.close();
	}
	catch(Exception e){
		out.println(e+"::3");
		String insert ="INSERT INTO cs_ows_transfer_email_log([order_no],[time_sent],[rep_no],[product_id],[from_email],[to_email],[user_id])VALUES(?,?,?,?,?,?,?) ";

		PreparedStatement update_mat_shop_orders = myConn.prepareStatement(insert);
		update_mat_shop_orders.setString(1,order_no);
		update_mat_shop_orders.setTimestamp(2,new java.sql.Timestamp(Calendar.getInstance().getTime().getTime()));
		update_mat_shop_orders.setString(3,rep_no);
		update_mat_shop_orders.setString(4,"ERROR3");
		update_mat_shop_orders.setString(5,from);
		update_mat_shop_orders.setString(6,to);
		update_mat_shop_orders.setString(7,userId);
		int rocount = update_mat_shop_orders.executeUpdate();
		update_mat_shop_orders.close();
	}
	//stmt.close();
	//myConn.close();
	%>
	<body>
	</body>
</html>
<%
}
  catch(Exception e){
	out.println("ERROR::"+e);
  }
%>