<jsp:useBean id="erapidBean" class="com.csgroup.general.ErapidBean" scope="application"/>
<%
if(erapidBean.getServerName()==null||erapidBean.getServerName().equals("null")||erapidBean.getServerName().trim().length()==0){
        erapidBean.setServerName("server1");
}
try{
%>
<html>
	<head>
		<title>Order Write-up sheet Mailing</title>
		<link rel='stylesheet' href='../../../style1.css' type='text/css'/>
	</head>
	<body>
		<h1>EMail Notification::</h1>
		<%@ page language="java" import="javax.mail.*" import="java.util.*" import="java.math.*" import="java.sql.*" import="javax.mail.internet.*" import="javax.activation.*" import="java.net.*" import="java.text.*" errorPage="error.jsp" %>
		<%@ include file="../../../db_con.jsp"%>
		<%
		String order_no = request.getParameter("order_no");
		String to="ADSNEWTRANSFERS@c-sgroup.com";
		String from="ADSNEWTRANSFERS@c-sgroup.com";
		String host ="LEBHQ-SMTP01.c-sgroup.com";
		String subject = "Construction Specialties Order Sheet for \'"+order_no+"\' Project";
		String message = "";
		message = message+"ORDER TRANSFERRED::"+order_no+".";
		boolean sendemail=true;
		ResultSet rs1=stmt.executeQuery("select quote_origin from cs_project where order_no='"+order_no+"'");
		if(rs1 != null){
			while(rs1.next()){
				if(rs1.getString(1)!=null && (rs1.getString(1).equals("As Build")||rs1.getString(1).equals("change")||rs1.getString(1).equals("release")||rs1.getString(1).equals("revision")||rs1.getString(1).equals("submittal"))){
					sendemail=false;
				}
			}
		}
		rs1.close();
		String message_footer="\r\n";
		if(sendemail){
			try{
				message_footer=message_footer+"\n\n\n[THIS MESSAGE WAS AUTOGENERATED BY CONSTRUCTION SPECIALTIES QUOTE SYSTEM]";
				message_footer=message_footer+"\n====================";
				message_footer=message_footer+"\nThis email message and any files transmitted with it is for the sole ";
				message_footer=message_footer+"\nuse of the intended recipient(s) and may contain confidential and privileged ";
				message_footer=message_footer+"\ninformation. Any unauthorized review, use, disclosure or distribution of this";
				message_footer=message_footer+"\nemail content is prohibited. If you are not the intended recipient, please";
				message_footer=message_footer+"\ndestroy all paper and electronic copies of the original message.";
				message_footer=message_footer+"\n====================";
				/*
					Properties prop =System.getProperties();
					prop.put("mail.smtp.host",host);
					Session ses1  = Session.getDefaultInstance(prop,null);
					MimeMessage msg = new MimeMessage(ses1);
					msg.addFrom(new InternetAddress().parse(from));
					msg.addRecipients(Message.RecipientType.TO,new InternetAddress().parse(to));
					msg.setSubject(subject);
					// Create the message part
					BodyPart messageBodyPart = new MimeBodyPart();
					// Fill the message
					messageBodyPart.setText(message);

					Multipart multipart = new MimeMultipart();
					multipart.addBodyPart(messageBodyPart);

					//adding the footer
					messageBodyPart = new MimeBodyPart();
					messageBodyPart.setText(message_footer);
					multipart.addBodyPart(messageBodyPart);
					Transport.send(msg);
				*/
				Properties prop =System.getProperties();
				prop.put("mail.smtp.host",host);
				Session ses1  = Session.getDefaultInstance(prop,null);
				MimeMessage msg = new MimeMessage(ses1);
				msg.addFrom(new InternetAddress().parse(from));
				msg.setReplyTo(new InternetAddress().parse(from));
				msg.addRecipients(Message.RecipientType.TO,new InternetAddress().parse(to));
				msg.setSubject(order_no+" Transferred");
				BodyPart messageBodyPart = new MimeBodyPart();
				// Fill the message
				messageBodyPart.setText(message);
				Multipart multipart = new MimeMultipart();
				multipart.addBodyPart(messageBodyPart);
				// Part two is attachment
				//messageBodyPart = new MimeBodyPart();
				//DataSource source = new URLDataSource(new URL(url));
				//messageBodyPart.setDataHandler(new DataHandler(source));
				//messageBodyPart.setFileName(attachName);
				//multipart.addBodyPart(messageBodyPart);
				msg.setContent(multipart);
				messageBodyPart = new MimeBodyPart();
				messageBodyPart.setText(message_footer);
				multipart.addBodyPart(messageBodyPart);
				Transport.send(msg);


				out.println(" An Email has been successfully delivered<br> to following recipients:<br> "+to+"<br>");

			}
			catch(javax.mail.internet.AddressException ae){
				ae.printStackTrace();
				out.println(ae);

			}
			catch(javax.mail.MessagingException me){
				me.printStackTrace();
				out.println(me);

			}
			catch(Exception e){
				e.printStackTrace();
				out.println(e);

			}
		}

		stmt.close();
		myConn.close();
		%>
	<body onload='javascript:window.close();'>
	</body>
</html>
<%
}
catch(Exception e){
out.println(e);
}
%>