<%

out.println("<tr>");
out.println("<td align='left' width='100%' height='30' class='tdheader' colspan='6'>");
if(order_entry_indicator.equals("N")|order_entry_indicator==null|order_entry_indicator.trim().length()<=0){
out.println("Order Sheet generated by "+userName+"<BR>");
}else if(order_entry_indicator.equals("Y")){
	out.println("Order Sheet generated by "+userName+"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"+"Expired pricing used on the order");

}else{
	out.println("Order Sheet generated by "+userName+"<BR>");
}
out.println("</td>");
out.println("</tr>");
if(order_notes == null){
	order_notes="";
}

if(terr_rep != null && terr_rep.trim().length()>0){
	String terr_rep_name="";
	ResultSet rsTerr=stmt.executeQuery("SELECT rep_account FROM cs_reps where rep_no = '"+terr_rep+"' ");
	if(rsTerr != null){
		while(rsTerr.next()){
			terr_rep_name=rsTerr.getString(1);
		}
	}
	rsTerr.close();
	if(terr_rep_name==null){
		terr_rep_name="";
	}
	out.println("<tr>");
	out.println("<td width='100%' bordercolor='#C0C0C0' height='10%' class='tddash' colspan='6'>");
	out.println("<table border='1' cellpadding='0' cellspacing='0' width='100%' class='tb'>");
	out.println("<tr>");
	out.println("<td class='tdnodash' width='4%'>TERR REP#</td>");
	out.println("<td class='tdnodash' width='24%'>&nbsp;<b>"+terr_rep+"</b></td>");
	out.println("<td class='tdnodash' width='12%'>REP NAME:</td>");
	out.println("<td class='tdnodash' width='65%'>&nbsp;<b>"+terr_rep_name+"</b></td>");
	out.println("</tr>");
	out.println("</table></td>");
  	out.println("</tr>");
}

if(spec_rep != null && spec_rep.trim().length()>0){
	String spec_rep_name="";
	ResultSet rsSpec=stmt.executeQuery("SELECT rep_account FROM cs_reps where rep_no = '"+spec_rep+"' ");
	if(rsSpec != null){
		while(rsSpec.next()){
			spec_rep_name=rsSpec.getString(1);
		}
	}
	rsSpec.close();
	if(spec_rep_name==null){
		spec_rep_name="";
	}
	out.println("<tr>");
	out.println("<td width='100%' bordercolor='#C0C0C0' height='10%' class='tddash' colspan='6'>");
	out.println("<table border='1' cellpadding='0' cellspacing='0' width='100%' class='tb'>");
	out.println("<tr>");
	out.println("<td class='tdnodash' width='4%'>SPEC REP#</td>");
	out.println("<td class='tdnodash' width='24%'>&nbsp;<b>"+spec_rep+"</b></td>");
	out.println("<td class='tdnodash' width='12%'>REP NAME:</td>");
	out.println("<td class='tdnodash' width='65%'>&nbsp;<b>"+spec_rep_name+"</b></td>");
	out.println("</tr>");
	out.println("</table></td>");
  	out.println("</tr>");
}




if(product.equals("LVR")){
	//out.println("HERE");
	if(extra_order_notes != null && extra_order_notes.trim().length()>0){
		//out.println("HERE2");
		out.println("<tr>");
		out.println("<td align='LEFT' width='100%' height='30' class='tdheader' colspan='6'>"+"&nbsp;ADDS/DEDUCTS TAKEN:"+extra_order_notes+"</td>");
		out.println("</tr>");
	}
}







out.println("<tr>");
out.println("<td align='center' width='100%' height='30' class='tdheader' colspan='6'>"+"&nbsp;NOTES"+"</td>");
out.println("</tr>");

		out.println("<tr>");
		out.println("<td width='100%' height='10%' class='tddash' bordercolor='#C0C0C0' colspan='6'>"+"&nbsp;"+order_notes+"<td>");
		out.println("</tr>");
		out.println("<tr>");
		out.println("<td width='100%' height='10%' class='tddash' bordercolor='#C0C0C0' colspan='6'>"+"&nbsp;"+cust_order_notes+"<td>");
		out.println("</tr>");
		out.println("<tr>");
		out.println("<td width='100%' height='10%' class='tddash' bordercolor='#C0C0C0' colspan='6'>"+"&nbsp;"+"<td>");
		out.println("</tr>");

out.println("</table>");
//out.println("Test"+for12.format((factor/(totprice_dis-((new Double(overage).doubleValue())+(new Double(handling_cost).doubleValue())+(new Double(freight_cost).doubleValue())))))+"factor:"+factor+"tot:"+totprice_dis+"over:"+overage+"hand:"+handling_cost+"freigh:"+freight_cost+"%"+for12.format((factor/((totprice_dis-(new Double(overage).doubleValue())+(new Double(handling_cost).doubleValue())+(new Double(freight_cost).doubleValue()))))*100)+"Test");
//out.println("<br>total"+(totprice_dis-((new Double(overage).doubleValue())+(new Double(handling_cost).doubleValue())+(new Double(freight_cost).doubleValue())))+"overage"+(new Double(overage).doubleValue())+"hand"+(new Double(handling_cost).doubleValue())+"freight"+(new Double(freight_cost).doubleValue()));

 %>
</body>
</html>
